name: Rust static build and publish

on: [push]
#  push:
#    tags:
#      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: khm

jobs:
  build:
    name: Build static binary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_target: x86_64-unknown-linux-musl
            platform_name: linux-amd64-musl
            build_type: musl
          - os: ubuntu-latest
            build_target: x86_64-unknown-linux-gnu
            platform_name: linux-amd64
            build_type: dynamic
          - os: windows-latest
            build_target: x86_64-pc-windows-msvc
            platform_name: windows-amd64
            build_type: default
          - os: macos-latest
            build_target: aarch64-apple-darwin
            platform_name: macos-arm64
            build_type: default
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      
      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-
      
      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - uses: dtolnay/rust-toolchain@stable
      
      - name: Install rust targets
        run: rustup target add ${{ matrix.build_target }}
        
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'dynamic'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config libgtk-3-dev libglib2.0-dev libcairo2-dev libpango1.0-dev libatk1.0-dev libgdk-pixbuf2.0-dev libxdo-dev
          
      - name: Build Linux Dynamic
        if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'dynamic'
        run: cargo build --target ${{ matrix.build_target }} --release
        
      - name: Build Linux MUSL (no GUI)
        if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'musl'
        uses: gmiam/rust-musl-action@master
        with:
          args: |
            cargo build --target ${{ matrix.build_target }} --release --no-default-features --features server
          
      - name: Build MacOS
        if: matrix.os == 'macos-latest'
        run: cargo build --target ${{ matrix.build_target }} --release
          
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: cargo build --target ${{ matrix.build_target }} --release
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}_${{ matrix.platform_name }}
          path: target/${{ matrix.build_target }}/release/${{ env.BINARY_NAME }}*

  release:
    name: Create Release Page
    if: always()  # Always run even if some builds fail
    needs: build
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload:
    name: Upload Release Assets
    if: always()  # Always run even if some builds fail
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform_name: linux-amd64-musl
          - os: ubuntu-latest
            platform_name: linux-amd64
          - os: windows-latest
            platform_name: windows-amd64
          - os: macos-latest
            platform_name: macos-arm64
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        name: Download ${{ matrix.platform_name }} artifact
        with:
          name: ${{ env.BINARY_NAME }}_${{ matrix.platform_name }}
          path: ${{ env.BINARY_NAME }}_${{ matrix.platform_name }}
        continue-on-error: true  # Continue if artifact doesn't exist
          
      - name: Check if artifact exists
        id: check_artifact
        run: |
          if [ -f "${{ env.BINARY_NAME }}_${{ matrix.platform_name }}/${{ env.BINARY_NAME }}${{ matrix.platform_name == 'windows-amd64' && '.exe' || '' }}" ]; then
            echo "artifact_exists=true" >> $GITHUB_OUTPUT
          else
            echo "artifact_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload Release Asset
        if: steps.check_artifact.outputs.artifact_exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ env.BINARY_NAME }}_${{ matrix.platform_name }}/${{ env.BINARY_NAME }}${{ matrix.platform_name == 'windows-amd64' && '.exe' || '' }}
          asset_name: ${{ env.BINARY_NAME }}_${{ matrix.platform_name }}${{ matrix.platform_name == 'windows-amd64' && '.exe' || '' }}
          asset_content_type: application/octet-stream

  build_docker:
    name: Build and Publish Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        name: Download Linux MUSL artifact
        with:
          name: ${{ env.BINARY_NAME }}_linux-amd64-musl
          path: .
          
      - name: ls
        run: |
          ls -lah
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ultradesu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set exec flag
        run: |
          chmod +x ${{ env.BINARY_NAME }}
          
      - name: Set outputs
        id: get_tag
        run: |
          echo "tag=$(echo ${GITHUB_REF} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ultradesu/${{ env.BINARY_NAME }}:latest,ultradesu/${{ env.BINARY_NAME }}:${{ steps.get_tag.outputs.tag }}

