name: Rust CI

on:
  push:
    tags:
      - 'v*.*.*'  # Запуск при создании новой тэгированной версии
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install target
      run: rustup target add ${{ matrix.target }}

    - name: Build project
      run: cargo build --release --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --target ${{ matrix.target }}

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: khm-${{ matrix.os }}
        path: target/${{ matrix.target }}/release/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Linux build artifact
      uses: actions/download-artifact@v4
      with:
        name: khm-ubuntu-latest
        path: target/x86_64-unknown-linux-gnu/release/

    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: khm-windows-latest
        path: target/x86_64-pc-windows-msvc/release/

    - name: Download macOS build artifact
      uses: actions/download-artifact@v4
      with:
        name: khm-macos-latest
        path: target/x86_64-apple-darwin/release/

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifacts: "target/x86_64-apple-darwin/release/khm,target/x86_64-pc-windows-msvc/release/khm.exe,target/x86_64-unknown-linux-gnu/release/khm"
        #bodyFile: "body.md"
